### ISSUE TITLE
GOAT on other Multi Omics Datasets

### ISSUE THREAD

**Issue by tAndreani** [DabinJeong/Multi-omics_biomarker#1]
Hello,  
thank you very much for providing GOAT to the community. I have been able to reproduce the results of your paper and i was wondering if the tool could be applied for another multi omics data. I have different data modalities from the same patient together with clinical data and i would like to test the method on them.

Any reply would be really appreicated.

Thank you in advance,
Tommaso

**Comment by DabinJeong** [comment]
Dear Tommaso,

Currently, our method is executable with methylome, transcriptome, proteome, and metabolome data.
With slight modification on gene prioritization step in stage 1 and preprocessing step in stage 2, it can be applicable to other modalities if gene-level features are measured.
Could you specify which data modalities you have? Then, I could narrow down which part should be modified.

Best regards,
Dabin
