### ISSUE TITLE
Questions about the 'input_graph' and 'teleport_graph'?

### ISSUE THREAD

**Issue by yeqing97** [DabinJeong/Multi-omics_biomarker#2]
Hi, thanks for your great work! I'm currently attempting to execute the 'network_propagation.py' script. 
I'm a bit confused about the input data requirements for 'input_graph' and 'teleport_graph'. Could you please explain the meaning of the data and provide guidance on where to locate the necessary input data?

**Comment by DabinJeong** [comment]
Dear yeqing,
I'm glad that you're interested in my work! Thank you.

For network propagation proposed here, we used two types of graph that is (1) protein-protein interaction graph from STRING database and (2) gene functional similarity graph constructed based gene-ontology(GO) database. 

1. 'input_graph' is processed by "/modules/filter_exp.py" and "modules/instantiate_nwk.py" script, which is edge filtering step given STRING database ("/data/PPI_human.tsv"). This step give weights to each edge of STRING database, as a correlation coefficient of connected nodes by the edge.
2. 'teleport' graph is processed by "/modules/GO_similarity_nwk.py", which is construction of functional similarity graph from GO database ("GO_basic/GO_tree.tsv" and "GO_basic/goa_human.gaf.filt"). Although STRING database contains extensive protein-protein interactions, it is hard to detect relationships between proteins with similar functions but not directly interacting. Thus, we construct edges inferred from GO database which implies functional similarity between two proteins.

For all inputs required for the "network_propagation.py" step, please refer to the "propagation" process in "biomarker_discovery.nf" script. It takes outputs from previous process "seed generation" and "TrainTestSplit" process and files specified in "pipeline.config" file. For detail, please refer to the "propagation" step in "workflow" at the end of the "biomarker_discovery.nf" file.

If you have any further questions, please feel free to ask me anytime!

Thanks,
Dabin

**Comment by yeqing97** [comment]
Thank you so much for the prompt and clear response! Your explanation was incredibly helpful, and I appreciate the effort you put into addressing my question.
